# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end


song_data = [["Cry", "Benson Boone", "Fireworks & Rollerblades"],
["MASC (feat. Teezo Touchdown)", "Doja Cat", "Scarlet 2 CLAUDE"],
["Crocodile Tearz", "J. Cole", "Might Delete Later"],
["Prep-School Gangsters", "Vampire Weekend", "Only God Was Above Us"],
["Wanna Be (with Megan Thee Stallion)", "GloRilla", "Ehhthang Ehhthang"],
["After Hours", "Kehlani", "After Hours"],
["Ciao!", "Bryson Tiller", "Bryson Tiller"],
["Eyes Closed", "Imagine Dragons", "Eyes Closed"],
["Creatures in Heaven", "Glass Animals", "Creatures In Heaven"],
["Drunk, Running", "Lizzy McAlpine", "Older"],
["Natanael Cano: Bzrp Music Sessions, Vol. 59",
 "Bizarrap",
 "Natanael Cano: Bzrp Music Sessions, Vol. 59"],
["Potato Loaded (feat. Destroy Lonely)",
 "Quavo",
 "Potato Loaded (feat. Destroy Lonely)"],
["1+1=11 - Edit", "Peggy Gou", "1+1=11"],
["Keep It Up", "Good Neighbours", "Keep It Up"],
["Fainted Love", "Conan Gray", "Found Heaven"],
["Utopia", "ODIE", "N.F.A. DEMOS"],
["Stick Around", "Medium Build", "Country"],
["Good Luck, Babe!", "Chappell Roan", "Good Luck, Babe!"],
["Overtime (feat. Kacey Musgraves)",
 "Rainbow Kitten Surprise",
 "Overtime (feat. Kacey Musgraves)"],
["I Don't Wanna Wait", "David Guetta", "I Don't Wanna Wait"],
["Club classics", "Charli XCX", "Club classics / B2b"],
["My Oh My", "Ava Max", "My Oh My"],
["princess peach", "Young Miko", "att."],
["Femme Fatale (feat. Coi Leray & Kaliii)",
 "G-Eazy",
 "Femme Fatale (feat. Coi Leray & Kaliii)"],
["86Sentra", "NxWorries", "86Sentra"],
["Spite", "Omar Apollo", "Spite"],
["Pillow In My Arms", "Griff", "ver2igo vol. 2"],
["On The Game", "The Black Keys", "Ohio Players"],
["Country House", "Sam Hunt", "Locked Up"],
["Please Don't Fall In Love With Me",
 "Khalid",
 "Please Don't Fall In Love With Me"],
["7 Minute Drill", "J. Cole", "Might Delete Later"],
["Bless (feat. Young Thug)", "Lil Wayne", "Bless"],
["HUMO", "Chencho Corleone", "HUMO"],
["Lejos de Ti", "The Marías", "Lejos de Ti"],
["Incredible (feat. Labrinth)", "Sia", "Incredible (feat. Labrinth)"],
["Comin’ Around Again", "Amber Mark", "Comin’ Around Again"],
["MADONNA & RIHANNA", "Rich Amiri", "MADONNA & RIHANNA"],
["Delilah", "Marcus King", "Mood Swings"],
["Wish I Never Felt", "Nate Smith", "Through the Smoke"],
["Love You, Miss You, Mean It", "Luke Bryan", "Love You, Miss You, Mean It"],
["Hold Me Up (Thank You)", "Khruangbin", "A LA SALA"],
["Co-Pathetic", "Novo Amor", "Collapse List"],
["Good Time", "Cage The Elephant", "Good Time"],
["Dream State", "Kamasi Washington", "Dream State"],
["Brindo Con Agua", "Aventura", "Brindo Con Agua"],
["Santa", "Rvssian", "Santa"],
["Nothing Ever Changes", "Vintage Culture", "Nothing Ever Changes"],
["Birthday", "41", "Birthday"],
["WHERE YO DADDY? (feat. KARRAHBOOO)", "Concrete Boys", "It's Us Vol. 1"],
["thing u do", "Tori Kelly", "TORI."],
["Small Town Scandal", "Zolita", "Small Town Scandal"],
["Self Sabotage", "Katie Pruitt", "Mantras"],
["Smoke On the Highway", "X Ambassadors", "Townie"],
["Shipwreck", "Mount Kimbie", "Shipwreck"],
["Heaven or Not", "Diplo", "Heaven or Not"],
["UNDERDOG SONG (feat. Lil Baby)", "Lil Mabu", "YOUNG GENIUS"],
["This Is The Way (feat. DMX)",
 "Five Finger Death Punch",
 "AfterLife (Deluxe)"],
["Devil I’ve Been", "Chayce Beckham", "Bad For Me"],
["Keep Your Head Up", "We Are Messengers", "Where The Joy Is"],
["Close My Eyes", "Luke Hemmings", "Close My Eyes"],
["Una Vida Pasada", "Camilo", "Una Vida Pasada"],
["Business As Usual (night shift mix)", "Eliza Rose", "Business As Usual"],
["Hiding (feat. Arizona Zervas)",
 "Two Friends",
 "Hiding (feat. Arizona Zervas)"],
["USC", "Chikoruss", "USC"],
["Cartwheels", "Soft Launch", "Cartwheels"],
["Pandora", "Wisp", "Pandora"],
["Bob Dylan Bus (feat. King Isis)",
 "Kenny Mason",
 "Pigeons & Planes presents: See You Next Year 2"],
["2Humpy is Back", "2Rare", "2Humpy is Back"],
["I Know", "6arelyhuman", "Internet Famous"],
["Karma", "JoJo Siwa", "Karma"],
["Time - Edit", "Carlita", "Time"],
["Earrings", "Malcolm Todd", "Sweet Boy"],
["Momma's Been Hurting",
 "Oliver Anthony Music",
 "Hymnal Of A Troubled Man's Mind"],
["my place", "Carly Pearce", "my place"],
["Here To Stay", "Jalen Ngonda", "Here To Stay"],
["i cant fall asleep", "Phora", "heartbreak hotel 2"],
["daddy of mine", "Four Year Strong", "daddy of mine"],
["Get It Right", "Bnny", "One Million Love Songs"],
["Wide As Heaven", "Phosphorescent", "Revelator"],
["Good As It Gets", "Blanco Brown", "Heartache & Lemonade"],
["Stranger To Me", "Waylon Wyatt", "Stranger To Me"],
["Eat Pray Love", "Paul Russell", "Eat Pray Love"],
["Die Trying", "aespa", "Die Trying"],
["joycelyn's dance", "berlioz", "joycelyn's dance"],
["Workin’ On It", "Brijean", "Workin' On It"],
["Heartless feat. Ikky", "Jay Sean", "Heartless feat. Ikky"],
["EXXACTLY", "TisaKorean", "MUMU 8818"],
["The Weekend", "Anti Up", "The Weekend / Control the Media"],
["What Does it Mean", "Gustaf", "Package Pt. 2"],
["Mine", "Michael Gerow", "Mine"],
["Bud Light The Way", "Owen Riegling", "Bud Light The Way"],
["Same Drunk", "Walker Hayes", "Sober Thoughts"],
["In The Cards", "Jamie Miller", "In The Cards"],
["Drive ft. KIDDO", "Steve Aoki", "Drive ft. KIDDO"],
["Forever", "Fabiana Palladino", "Fabiana Palladino"],
["I Hate You In The Morning", "Otha", "I Hate You In The Morning"],
["Life After You", "Julia Cole", "Life After You"],
["Faltas Tú", "Morat", "Faltas Tú"],
["back to him", "Amelia Moore", "he's just not that into you!"]]




for song in song_data
  title, artist, album = *song
  date = Faker::Date.between(from: '2024-04-01', to: '2024-05-16')
  entry = Song.new(title: title, artist: artist, album: album, release_date: date)
  entry.save
end


