DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS playlist;
DROP TABLE IF EXISTS playlist_song;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE song (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  artist TEXT NOT NULL,
  title TEXT NOT NULL,
  album TEXT NOT NULL,
  url TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (author_id) REFERENCES user (id)
);


CREATE TABLE playlist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  FOREIGN KEY (user_id) REFERENCES user (id),

  title TEXT NOT NULL,
  description TEXT NOT NULL,
);


CREATE TABLE playlist_song (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  FOREIGN KEY (playlist_id) REFERENCES playlist (id),
  FOREIGN KEY (song_id) REFERENCES song (id),
);